### ISSUE TITLE
Add Address as a ValueObject

### ISSUE THREAD

**Issue by lukebouch** [michael-rubel/laravel-value-objects#36]
Are there any plans to add an `Address` value object?

**Comment by michael-rubel** [comment]
@lukebouch we've created a custom Address VO for the country we work with. Every country has its own address format, so that would be a huge job to make an extendable object like that with the support of every country.

If you have an idea of how to make that universal and maintainable, you're free to submit pull requests. 🤝

**Comment by lukebouch** [comment]
@michael-rubel, that makes sense.
